import { NextResponse } from "next/server";

import { requireUser } from "@/lib/auth";

/**
 * GET /api/v1/services
 *
 * Lists all available generation services with their capabilities.
 * Useful for programmatic clients to discover what's available.
 */
export async function GET(request: Request) {
  try {
    await requireUser(request);

    return NextResponse.json({
      success: true,
      services: [
        {
          id: "video:t2v",
          name: "Wan 2.6 Text-to-Video",
          endpoint: "wan-2-6-t2v",
          type: "video",
          inputType: "text",
          requiresImage: false,
          parameters: {
            prompt: { type: "string", required: true },
            negativePrompt: { type: "string", required: false },
            duration: { type: "number", options: [5, 10, 15], default: 5 },
            resolution: { type: "string", options: ["720p", "1080p"], default: "720p" },
          },
        },
        {
          id: "video:i2v",
          name: "Wan 2.6 Image-to-Video",
          endpoint: "wan-2-6-i2v",
          type: "video",
          inputType: "image",
          requiresImage: true,
          parameters: {
            prompt: { type: "string", required: true },
            negativePrompt: { type: "string", required: false },
            duration: { type: "number", options: [5, 10, 15], default: 5 },
            resolution: { type: "string", options: ["720p", "1080p"], default: "720p" },
            sourceFile: { type: "file", required: true, accept: "image/*" },
          },
        },
        {
          id: "video:fal-i2v",
          name: "Wan 2.6 Image-to-Video (fal.ai)",
          provider: "fal.ai",
          endpoint: "wan/v2.6/image-to-video",
          type: "video",
          inputType: "image",
          requiresImage: true,
          safetyFilter: "disabled",
          pricing: { "720p": "$0.10/sec", "1080p": "$0.15/sec" },
          tags: ["image-to-video"],
          parameters: {
            prompt: { type: "string", required: true, maxLength: 800 },
            negativePrompt: { type: "string", required: false, maxLength: 500 },
            duration: { type: "string", options: ["5", "10", "15"], default: "5" },
            resolution: { type: "string", options: ["720p", "1080p"], default: "1080p" },
            sourceFile: { type: "file", required: true, accept: "image/*", description: "First frame image. Dimensions 240-7680 px." },
            audioFile: { type: "file", required: false, accept: "audio/wav,audio/mp3", maxSizeMB: 15, description: "Background audio (WAV/MP3, 3-30s, max 15MB)" },
            enablePromptExpansion: { type: "boolean", default: true, description: "Whether to rewrite the prompt using an LLM." },
            multiShots: { type: "boolean", default: false, description: "Intelligent multi-shot segmentation; only active when enablePromptExpansion is true." },
            seed: { type: "number", required: false, min: 0, max: 2147483647 },
          },
        },
        {
          id: "video:fal-i2v-2.7",
          name: "Wan 2.7 Image-to-Video (fal.ai)",
          provider: "fal.ai",
          endpoint: "fal-ai/wan/v2.7/image-to-video",
          type: "video",
          inputType: "image",
          requiresImage: false,
          safetyFilter: "disabled",
          pricing: "$0.10/sec",
          tags: ["stylized", "transform", "lipsync"],
          parameters: {
            prompt: { type: "string", required: false, maxLength: 5000 },
            negativePrompt: { type: "string", required: false, maxLength: 500 },
            duration: { type: "number", options: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], default: 5 },
            resolution: { type: "string", options: ["720p", "1080p"], default: "1080p" },
            sourceFile: { type: "file", required: false, accept: "image/png,image/jpeg,image/webp,image/bmp", maxSizeMB: 20, description: "Start frame image (JPEG/PNG/BMP/WEBP, max 20MB)" },
            endImageFile: { type: "file", required: false, accept: "image/png,image/jpeg,image/webp,image/bmp", maxSizeMB: 20, description: "End frame image for first-and-last-frame-to-video" },
            videoClipFile: { type: "file", required: false, accept: "video/mp4,video/quicktime", maxSizeMB: 100, description: "Video clip to continue from (MP4/MOV, 2-10s, max 100MB). Mutually exclusive with sourceFile." },
            audioFile: { type: "file", required: false, accept: "audio/wav,audio/mp3", maxSizeMB: 15, description: "Driving audio (WAV/MP3, 2-30s, max 15MB)" },
            enablePromptExpansion: { type: "boolean", default: true },
            seed: { type: "number", required: false, min: 0, max: 2147483647 },
          },
        },
        {
          id: "video:atlas-seedance-i2v",
          name: "Seedance 2.0 Image-to-Video (Atlas Cloud)",
          provider: "atlas-cloud",
          endpoint: "bytedance/seedance-2.0/image-to-video",
          type: "video",
          inputType: "image",
          requiresImage: true,
          safetyFilter: "atlas-relaxed",
          pricing: "$0.10/sec",
          tags: ["atlas-cloud", "seedance-2.0", "realistic-faces-allowed", "native-audio"],
          parameters: {
            prompt: { type: "string", required: true },
            sourceFile: { type: "file", required: true, accept: "image/*", description: "Start frame image" },
            endImageFile: { type: "file", required: false, accept: "image/*", description: "Optional end frame for last-frame-to-video" },
            duration: { type: "number", options: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, -1], default: 5, description: "4-15 seconds or -1 for auto" },
            atlasResolution: { type: "string", options: ["480p", "720p", "1080p"], default: "720p" },
            atlasRatio: { type: "string", options: ["adaptive", "21:9", "16:9", "4:3", "1:1", "3:4", "9:16"], default: "adaptive" },
            atlasGenerateAudio: { type: "boolean", default: true },
            atlasWatermark: { type: "boolean", default: false },
            atlasReturnLastFrame: { type: "boolean", default: false },
            seed: { type: "number", required: false, min: 0, max: 2147483647 },
          },
        },
        {
          id: "video:atlas-seedance-fast-i2v",
          name: "Seedance 2.0 Fast Image-to-Video (Atlas Cloud)",
          provider: "atlas-cloud",
          endpoint: "bytedance/seedance-2.0-fast/image-to-video",
          type: "video",
          inputType: "image",
          requiresImage: true,
          safetyFilter: "atlas-relaxed",
          pricing: "$0.081/sec",
          tags: ["atlas-cloud", "seedance-2.0-fast", "realistic-faces-allowed"],
          parameters: {
            prompt: { type: "string", required: true },
            sourceFile: { type: "file", required: true, accept: "image/*", description: "Start frame image" },
            endImageFile: { type: "file", required: false, accept: "image/*", description: "Optional end frame" },
            duration: { type: "number", options: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, -1], default: 5 },
            atlasResolution: { type: "string", options: ["480p", "720p", "1080p"], default: "720p" },
            atlasRatio: { type: "string", options: ["adaptive", "21:9", "16:9", "4:3", "1:1", "3:4", "9:16"], default: "adaptive" },
            atlasGenerateAudio: { type: "boolean", default: true },
            atlasWatermark: { type: "boolean", default: false },
            atlasReturnLastFrame: { type: "boolean", default: false },
            seed: { type: "number", required: false, min: 0, max: 2147483647 },
          },
        },
        {
          id: "video:atlas-seedance-r2v",
          name: "Seedance 2.0 Reference-to-Video (Atlas Cloud)",
          provider: "atlas-cloud",
          endpoint: "bytedance/seedance-2.0/reference-to-video",
          type: "video",
          inputType: "reference",
          requiresImage: false,
          safetyFilter: "atlas-relaxed",
          pricing: "$0.10/sec",
          tags: ["atlas-cloud", "multi-image", "multi-video", "video-extension"],
          parameters: {
            prompt: { type: "string", required: true },
            atlasRefImages: { type: "file[]", required: false, accept: "image/*", min: 0, max: 9, description: "Up to 9 reference images for multi-image/character consistency" },
            atlasRefVideos: { type: "file[]", required: false, accept: "video/*", min: 0, max: 3, description: "Up to 3 reference videos (≤15s total) for editing/extension" },
            atlasRefAudios: { type: "file[]", required: false, accept: "audio/*", min: 0, max: 3, description: "Up to 3 audio clips (≤15s total)" },
            duration: { type: "number", options: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, -1], default: 5 },
            atlasResolution: { type: "string", options: ["480p", "720p", "1080p"], default: "720p" },
            atlasRatio: { type: "string", options: ["adaptive", "21:9", "16:9", "4:3", "1:1", "3:4", "9:16"], default: "adaptive" },
            atlasGenerateAudio: { type: "boolean", default: true },
            atlasWatermark: { type: "boolean", default: false },
            seed: { type: "number", required: false, min: 0, max: 2147483647 },
          },
        },
        {
          id: "video:atlas-seedance-fast-r2v",
          name: "Seedance 2.0 Fast Reference-to-Video (Atlas Cloud)",
          provider: "atlas-cloud",
          endpoint: "bytedance/seedance-2.0-fast/reference-to-video",
          type: "video",
          inputType: "reference",
          requiresImage: false,
          safetyFilter: "atlas-relaxed",
          pricing: "$0.081/sec",
          tags: ["atlas-cloud", "multi-image", "multi-video"],
          parameters: {
            prompt: { type: "string", required: true },
            atlasRefImages: { type: "file[]", required: false, accept: "image/*", min: 0, max: 9 },
            atlasRefVideos: { type: "file[]", required: false, accept: "video/*", min: 0, max: 3 },
            atlasRefAudios: { type: "file[]", required: false, accept: "audio/*", min: 0, max: 3 },
            duration: { type: "number", options: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, -1], default: 5 },
            atlasResolution: { type: "string", options: ["480p", "720p", "1080p"], default: "720p" },
            atlasRatio: { type: "string", options: ["adaptive", "21:9", "16:9", "4:3", "1:1", "3:4", "9:16"], default: "adaptive" },
            atlasGenerateAudio: { type: "boolean", default: true },
            atlasWatermark: { type: "boolean", default: false },
            seed: { type: "number", required: false, min: 0, max: 2147483647 },
          },
        },
        {
          id: "video:atlas-seedance-t2v",
          name: "Seedance 2.0 Text-to-Video (Atlas Cloud)",
          provider: "atlas-cloud",
          endpoint: "bytedance/seedance-2.0/text-to-video",
          type: "video",
          inputType: "text",
          requiresImage: false,
          safetyFilter: "atlas-relaxed",
          pricing: "$0.10/sec",
          tags: ["atlas-cloud"],
          parameters: {
            prompt: { type: "string", required: true },
            duration: { type: "number", options: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, -1], default: 5 },
            atlasResolution: { type: "string", options: ["480p", "720p", "1080p"], default: "720p" },
            atlasRatio: { type: "string", options: ["adaptive", "21:9", "16:9", "4:3", "1:1", "3:4", "9:16"], default: "adaptive" },
            atlasGenerateAudio: { type: "boolean", default: true },
            seed: { type: "number", required: false, min: 0, max: 2147483647 },
          },
        },
        {
          id: "video:atlas-seedance-fast-t2v",
          name: "Seedance 2.0 Fast Text-to-Video (Atlas Cloud)",
          provider: "atlas-cloud",
          endpoint: "bytedance/seedance-2.0-fast/text-to-video",
          type: "video",
          inputType: "text",
          requiresImage: false,
          safetyFilter: "atlas-relaxed",
          pricing: "$0.081/sec",
          tags: ["atlas-cloud"],
          parameters: {
            prompt: { type: "string", required: true },
            duration: { type: "number", options: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, -1], default: 5 },
            atlasResolution: { type: "string", options: ["480p", "720p", "1080p"], default: "720p" },
            atlasRatio: { type: "string", options: ["adaptive", "21:9", "16:9", "4:3", "1:1", "3:4", "9:16"], default: "adaptive" },
            atlasGenerateAudio: { type: "boolean", default: true },
            seed: { type: "number", required: false, min: 0, max: 2147483647 },
          },
        },
        {
          id: "video:fal-r2v-2.7",
          name: "Wan 2.7 Reference-to-Video (fal.ai)",
          provider: "fal.ai",
          endpoint: "fal-ai/wan/v2.7/reference-to-video",
          type: "video",
          inputType: "reference",
          requiresImage: false,
          safetyFilter: "disabled",
          pricing: "$0.10/sec (input video duration + output video duration)",
          tags: ["stylized", "transform", "lipsync"],
          parameters: {
            prompt: { type: "string", required: true, maxLength: 5000 },
            negativePrompt: { type: "string", required: false, maxLength: 500 },
            duration: { type: "number", options: [2, 3, 4, 5, 6, 7, 8, 9, 10], default: 5 },
            resolution: { type: "string", options: ["720p", "1080p"], default: "1080p" },
            aspectRatio: { type: "string", options: ["16:9", "9:16", "1:1", "4:3", "3:4"], default: "16:9" },
            referenceImages: { type: "file[]", required: false, accept: "image/*", maxSizeMB: 20, description: "Reference images for character/object appearance (multiple for multi-subject, max 20MB each)" },
            referenceVideos: { type: "file[]", required: false, accept: "video/*", maxSizeMB: 100, description: "Reference videos for motion/appearance (multiple for multi-subject, max 100MB each)" },
            multiShots: { type: "boolean", default: false, description: "Enable intelligent multi-shot segmentation" },
            seed: { type: "number", required: false, min: 0, max: 2147483647 },
          },
        },
        {
          id: "image:flux",
          name: "Flux 1 Kontext Dev (image-to-image)",
          endpoint: "black-forest-labs-flux-1-kontext-dev",
          type: "image",
          inputType: "image",
          requiresImage: true,
          safetyFilter: "disabled",
          parameters: {
            prompt: { type: "string", required: true },
            negativePrompt: { type: "string", required: false },
            sourceFile: { type: "file", required: true, accept: "image/*" },
          },
        },
        {
          id: "image:flux-dev",
          name: "Flux 1 Dev (text-to-image, quality)",
          endpoint: "black-forest-labs-flux-1-dev",
          type: "image",
          inputType: "text",
          requiresImage: false,
          safetyFilter: "disabled",
          parameters: {
            prompt: { type: "string", required: true },
            negativePrompt: { type: "string", required: false },
          },
        },
        {
          id: "image:flux-schnell",
          name: "Flux 1 Schnell (text-to-image, fast)",
          endpoint: "black-forest-labs-flux-1-schnell",
          type: "image",
          inputType: "text",
          requiresImage: false,
          safetyFilter: "disabled",
          parameters: {
            prompt: { type: "string", required: true },
            negativePrompt: { type: "string", required: false },
          },
        },
        {
          id: "image:qwen-t2i",
          name: "Qwen Image (text-to-image)",
          endpoint: "qwen-image-t2i",
          type: "image",
          inputType: "text",
          requiresImage: false,
          safetyFilter: "disabled",
          parameters: {
            prompt: { type: "string", required: true },
            negativePrompt: { type: "string", required: false },
          },
        },
        {
          id: "image:qwen",
          name: "Qwen Image Edit (image-to-image)",
          endpoint: "qwen-image-edit",
          type: "image",
          inputType: "image",
          requiresImage: true,
          safetyFilter: "disabled",
          parameters: {
            prompt: { type: "string", required: true },
            negativePrompt: { type: "string", required: false },
            sourceFile: { type: "file", required: true, accept: "image/*" },
          },
        },
        {
          id: "image:qwen-2511",
          name: "Qwen Image Edit 2511 (image-to-image)",
          endpoint: "qwen-image-edit-2511",
          type: "image",
          inputType: "image",
          requiresImage: true,
          safetyFilter: "none",
          parameters: {
            prompt: { type: "string", required: true },
            sourceFile: { type: "file", required: true, accept: "image/*" },
          },
        },
        {
          id: "image:p-edit",
          name: "P-Image Edit (image-to-image, $0.01)",
          endpoint: "p-image-edit",
          type: "image",
          inputType: "image",
          requiresImage: true,
          safetyFilter: "disabled",
          parameters: {
            prompt: { type: "string", required: true },
            sourceFile: { type: "file", required: true, accept: "image/*" },
          },
        },
        {
          id: "image:seedream-edit",
          name: "Seedream 4.0 Edit (image-to-image)",
          endpoint: "seedream-v4-edit",
          type: "image",
          inputType: "image",
          requiresImage: true,
          safetyFilter: "disabled",
          parameters: {
            prompt: { type: "string", required: true },
            sourceFile: { type: "file", required: true, accept: "image/*" },
          },
        },
        {
          id: "image:nano-banana",
          name: "Nano Banana Edit (image-to-image)",
          endpoint: "nano-banana-edit",
          type: "image",
          inputType: "image",
          requiresImage: true,
          safetyFilter: "disabled",
          parameters: {
            prompt: { type: "string", required: true },
            sourceFile: { type: "file", required: true, accept: "image/*" },
          },
        },
        {
          id: "image:z-turbo",
          name: "Z-Image Turbo (image-to-image)",
          endpoint: "z-image-turbo",
          type: "image",
          inputType: "image",
          requiresImage: true,
          safetyFilter: "disabled",
          parameters: {
            prompt: { type: "string", required: true },
            sourceFile: { type: "file", required: true, accept: "image/*" },
          },
        },
        {
          id: "image:fal-seedream-edit-4.5",
          name: "Seedream 4.5 Edit (fal.ai)",
          provider: "fal.ai",
          type: "image",
          inputType: "image",
          requiresImage: true,
          safetyFilter: "enabled",
          pricing: "$0.04/image",
          tags: ["stylized", "transform"],
          parameters: {
            prompt: { type: "string", required: true, description: "The text prompt used to edit the image. Reference images as 'Figure 1', 'Figure 2', etc." },
            imageSize: { type: "string", options: ["auto_4K", "square_hd", "landscape_16_9", "portrait_16_9", "landscape_4_3", "portrait_4_3"], default: "auto_4K" },
            numImages: { type: "number", min: 1, max: 6, default: 1, description: "Number of separate model generations" },
            maxImages: { type: "number", min: 1, max: 6, default: 1, description: "Max images per generation. Total output: numImages to maxImages*numImages" },
            editImages: { type: "file[]", required: true, accept: "image/*", min: 1, max: 10, description: "1-10 input images for editing" },
          },
        },
        {
          id: "image:fal-t2i-2.7",
          name: "Wan 2.7 Text-to-Image (fal.ai)",
          provider: "fal.ai",
          type: "image",
          inputType: "text",
          requiresImage: false,
          safetyFilter: "disabled",
          pricing: "$0.03/image",
          parameters: {
            prompt: { type: "string", required: true, maxLength: 5000, description: "Supports Chinese and English" },
            negativePrompt: { type: "string", required: false, maxLength: 500 },
            imageSize: { type: "string", options: ["square_hd", "square", "portrait_4_3", "portrait_16_9", "landscape_4_3", "landscape_16_9"], default: "square_hd" },
            numImages: { type: "number", min: 1, max: 5, default: 1 },
          },
        },
        {
          id: "image:fal-pro-t2i-2.7",
          name: "Wan 2.7 Pro Text-to-Image (fal.ai)",
          provider: "fal.ai",
          type: "image",
          inputType: "text",
          requiresImage: false,
          safetyFilter: "disabled",
          pricing: "premium",
          parameters: {
            prompt: { type: "string", required: true, maxLength: 5000, description: "Supports Chinese and English" },
            negativePrompt: { type: "string", required: false, maxLength: 500 },
            imageSize: { type: "string", options: ["square_hd", "square", "portrait_4_3", "portrait_16_9", "landscape_4_3", "landscape_16_9"], default: "square_hd" },
            numImages: { type: "number", min: 1, max: 5, default: 1 },
          },
        },
        {
          id: "image:fal-edit-2.7",
          name: "Wan 2.7 Edit (fal.ai)",
          provider: "fal.ai",
          type: "image",
          inputType: "image",
          requiresImage: true,
          safetyFilter: "disabled",
          pricing: "$0.03/image",
          parameters: {
            prompt: { type: "string", required: true, maxLength: 5000, description: "Reference images as 'image 1', 'image 2', etc. Supports Chinese and English" },
            negativePrompt: { type: "string", required: false, maxLength: 500 },
            imageSize: { type: "string", options: ["square_hd", "square", "portrait_4_3", "portrait_16_9", "landscape_4_3", "landscape_16_9"], default: "square_hd" },
            numImages: { type: "number", min: 1, max: 4, default: 1 },
            enablePromptExpansion: { type: "boolean", default: true },
            editImages: { type: "file[]", required: true, accept: "image/*", min: 1, max: 4, description: "1-4 reference images for editing" },
          },
        },
        {
          id: "image:fal-pro-edit-2.7",
          name: "Wan 2.7 Pro Edit (fal.ai)",
          provider: "fal.ai",
          type: "image",
          inputType: "image",
          requiresImage: true,
          safetyFilter: "disabled",
          pricing: "$0.075/image",
          parameters: {
            prompt: { type: "string", required: true, maxLength: 5000, description: "Reference images as 'image 1', 'image 2', etc. Supports Chinese and English" },
            negativePrompt: { type: "string", required: false, maxLength: 500 },
            imageSize: { type: "string", options: ["square_hd", "square", "portrait_4_3", "portrait_16_9", "landscape_4_3", "landscape_16_9"], default: "square_hd" },
            numImages: { type: "number", min: 1, max: 4, default: 1 },
            enablePromptExpansion: { type: "boolean", default: true },
            editImages: { type: "file[]", required: true, accept: "image/*", min: 1, max: 4, description: "1-4 reference images for editing" },
          },
        },
      ],
      supportedFileTypes: {
        image: ["image/png", "image/jpeg", "image/webp", "image/gif"],
        video: ["video/mp4", "video/webm", "video/mov"],
        "3d": [
          "model/gltf-binary",
          "model/gltf+json",
          "application/octet-stream",
          "model/obj",
          "model/stl",
          "model/fbx",
          "model/usdz",
          "model/step",
          "model/3mf",
        ],
      },
      supportedFileExtensions: {
        image: [".png", ".jpg", ".jpeg", ".webp", ".gif"],
        video: [".mp4", ".webm", ".mov", ".m4v"],
        "3d": [".glb", ".gltf", ".obj", ".stl", ".fbx", ".usdz", ".usdc", ".usd", ".step", ".stp", ".3mf", ".ply", ".abc"],
      },
    });
  } catch {
    return NextResponse.json({ success: false, message: "Unauthorized" }, { status: 401 });
  }
}
