import { NextResponse } from "next/server";

import { requireUser } from "@/lib/auth";

/**
 * GET /api/v1/services
 *
 * Lists all available generation services with their capabilities.
 * Useful for programmatic clients to discover what's available.
 */
export async function GET(request: Request) {
  try {
    await requireUser(request);

    return NextResponse.json({
      success: true,
      services: [
        {
          id: "video:t2v",
          name: "Wan 2.6 Text-to-Video",
          endpoint: "wan-2-6-t2v",
          type: "video",
          inputType: "text",
          requiresImage: false,
          parameters: {
            prompt: { type: "string", required: true },
            negativePrompt: { type: "string", required: false },
            duration: { type: "number", options: [5, 10, 15], default: 5 },
            resolution: { type: "string", options: ["720p", "1080p"], default: "720p" },
          },
        },
        {
          id: "video:i2v",
          name: "Wan 2.6 Image-to-Video",
          endpoint: "wan-2-6-i2v",
          type: "video",
          inputType: "image",
          requiresImage: true,
          parameters: {
            prompt: { type: "string", required: true },
            negativePrompt: { type: "string", required: false },
            duration: { type: "number", options: [5, 10, 15], default: 5 },
            resolution: { type: "string", options: ["720p", "1080p"], default: "720p" },
            sourceFile: { type: "file", required: true, accept: "image/*" },
          },
        },
        {
          id: "video:fal-i2v",
          name: "Wan 2.6 Image-to-Video (fal.ai)",
          provider: "fal.ai",
          type: "video",
          inputType: "image",
          requiresImage: true,
          safetyFilter: "disabled",
          pricing: { "720p": "$0.10/sec", "1080p": "$0.15/sec" },
          parameters: {
            prompt: { type: "string", required: true, maxLength: 800 },
            negativePrompt: { type: "string", required: false, maxLength: 500 },
            duration: { type: "string", options: ["5", "10", "15"], default: "5" },
            resolution: { type: "string", options: ["720p", "1080p"], default: "1080p" },
            sourceFile: { type: "file", required: true, accept: "image/*" },
            audioFile: { type: "file", required: false, accept: "audio/wav,audio/mp3", maxSizeMB: 15 },
          },
        },
        {
          id: "video:fal-i2v-2.7",
          name: "Wan 2.7 Image-to-Video (fal.ai)",
          provider: "fal.ai",
          type: "video",
          inputType: "image",
          requiresImage: false,
          safetyFilter: "disabled",
          pricing: "$0.10/sec",
          parameters: {
            prompt: { type: "string", required: false, maxLength: 5000 },
            negativePrompt: { type: "string", required: false, maxLength: 500 },
            duration: { type: "number", options: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], default: 5 },
            resolution: { type: "string", options: ["720p", "1080p"], default: "1080p" },
            sourceFile: { type: "file", required: false, accept: "image/*", description: "Start frame image" },
            endImageFile: { type: "file", required: false, accept: "image/*", description: "End frame image (first-and-last-frame-to-video)" },
            audioFile: { type: "file", required: false, accept: "audio/wav,audio/mp3", maxSizeMB: 15, description: "Driving audio (WAV/MP3, 2-30s)" },
            enablePromptExpansion: { type: "boolean", default: true },
          },
        },
        {
          id: "video:fal-r2v-2.7",
          name: "Wan 2.7 Reference-to-Video (fal.ai)",
          provider: "fal.ai",
          type: "video",
          inputType: "reference",
          requiresImage: false,
          safetyFilter: "disabled",
          pricing: "$0.10/sec",
          parameters: {
            prompt: { type: "string", required: true, maxLength: 5000 },
            negativePrompt: { type: "string", required: false, maxLength: 500 },
            duration: { type: "number", options: [2, 3, 4, 5, 6, 7, 8, 9, 10], default: 5 },
            resolution: { type: "string", options: ["720p", "1080p"], default: "1080p" },
            aspectRatio: { type: "string", options: ["16:9", "9:16", "1:1", "4:3", "3:4"], default: "16:9" },
            referenceImages: { type: "file[]", required: false, accept: "image/*", description: "Reference images for character/object appearance (multiple, max 20MB each)" },
            referenceVideos: { type: "file[]", required: false, accept: "video/*", description: "Reference videos for motion/appearance (multiple, max 100MB each)" },
            multiShots: { type: "boolean", default: false, description: "Enable multi-shot segmentation" },
          },
        },
        {
          id: "image:flux",
          name: "Flux 1 Kontext Dev (image-to-image)",
          endpoint: "black-forest-labs-flux-1-kontext-dev",
          type: "image",
          inputType: "image",
          requiresImage: true,
          safetyFilter: "disabled",
          parameters: {
            prompt: { type: "string", required: true },
            negativePrompt: { type: "string", required: false },
            sourceFile: { type: "file", required: true, accept: "image/*" },
          },
        },
        {
          id: "image:flux-dev",
          name: "Flux 1 Dev (text-to-image, quality)",
          endpoint: "black-forest-labs-flux-1-dev",
          type: "image",
          inputType: "text",
          requiresImage: false,
          safetyFilter: "disabled",
          parameters: {
            prompt: { type: "string", required: true },
            negativePrompt: { type: "string", required: false },
          },
        },
        {
          id: "image:flux-schnell",
          name: "Flux 1 Schnell (text-to-image, fast)",
          endpoint: "black-forest-labs-flux-1-schnell",
          type: "image",
          inputType: "text",
          requiresImage: false,
          safetyFilter: "disabled",
          parameters: {
            prompt: { type: "string", required: true },
            negativePrompt: { type: "string", required: false },
          },
        },
        {
          id: "image:qwen-t2i",
          name: "Qwen Image (text-to-image)",
          endpoint: "qwen-image-t2i",
          type: "image",
          inputType: "text",
          requiresImage: false,
          safetyFilter: "disabled",
          parameters: {
            prompt: { type: "string", required: true },
            negativePrompt: { type: "string", required: false },
          },
        },
        {
          id: "image:qwen",
          name: "Qwen Image Edit (image-to-image)",
          endpoint: "qwen-image-edit",
          type: "image",
          inputType: "image",
          requiresImage: true,
          safetyFilter: "disabled",
          parameters: {
            prompt: { type: "string", required: true },
            negativePrompt: { type: "string", required: false },
            sourceFile: { type: "file", required: true, accept: "image/*" },
          },
        },
        {
          id: "image:qwen-2511",
          name: "Qwen Image Edit 2511 (image-to-image)",
          endpoint: "qwen-image-edit-2511",
          type: "image",
          inputType: "image",
          requiresImage: true,
          safetyFilter: "none",
          parameters: {
            prompt: { type: "string", required: true },
            sourceFile: { type: "file", required: true, accept: "image/*" },
          },
        },
        {
          id: "image:p-edit",
          name: "P-Image Edit (image-to-image, $0.01)",
          endpoint: "p-image-edit",
          type: "image",
          inputType: "image",
          requiresImage: true,
          safetyFilter: "disabled",
          parameters: {
            prompt: { type: "string", required: true },
            sourceFile: { type: "file", required: true, accept: "image/*" },
          },
        },
        {
          id: "image:seedream-edit",
          name: "Seedream 4.0 Edit (image-to-image)",
          endpoint: "seedream-v4-edit",
          type: "image",
          inputType: "image",
          requiresImage: true,
          safetyFilter: "disabled",
          parameters: {
            prompt: { type: "string", required: true },
            sourceFile: { type: "file", required: true, accept: "image/*" },
          },
        },
        {
          id: "image:nano-banana",
          name: "Nano Banana Edit (image-to-image)",
          endpoint: "nano-banana-edit",
          type: "image",
          inputType: "image",
          requiresImage: true,
          safetyFilter: "disabled",
          parameters: {
            prompt: { type: "string", required: true },
            sourceFile: { type: "file", required: true, accept: "image/*" },
          },
        },
        {
          id: "image:z-turbo",
          name: "Z-Image Turbo (image-to-image)",
          endpoint: "z-image-turbo",
          type: "image",
          inputType: "image",
          requiresImage: true,
          safetyFilter: "disabled",
          parameters: {
            prompt: { type: "string", required: true },
            sourceFile: { type: "file", required: true, accept: "image/*" },
          },
        },
        {
          id: "image:fal-t2i-2.7",
          name: "Wan 2.7 Text-to-Image (fal.ai)",
          provider: "fal.ai",
          type: "image",
          inputType: "text",
          requiresImage: false,
          safetyFilter: "disabled",
          pricing: "$0.03/image",
          parameters: {
            prompt: { type: "string", required: true, maxLength: 5000, description: "Supports Chinese and English" },
            negativePrompt: { type: "string", required: false, maxLength: 500 },
            imageSize: { type: "string", options: ["square_hd", "square", "portrait_4_3", "portrait_16_9", "landscape_4_3", "landscape_16_9"], default: "square_hd" },
            numImages: { type: "number", min: 1, max: 5, default: 1 },
          },
        },
        {
          id: "image:fal-pro-t2i-2.7",
          name: "Wan 2.7 Pro Text-to-Image (fal.ai)",
          provider: "fal.ai",
          type: "image",
          inputType: "text",
          requiresImage: false,
          safetyFilter: "disabled",
          pricing: "premium",
          parameters: {
            prompt: { type: "string", required: true, maxLength: 5000, description: "Supports Chinese and English" },
            negativePrompt: { type: "string", required: false, maxLength: 500 },
            imageSize: { type: "string", options: ["square_hd", "square", "portrait_4_3", "portrait_16_9", "landscape_4_3", "landscape_16_9"], default: "square_hd" },
            numImages: { type: "number", min: 1, max: 5, default: 1 },
          },
        },
        {
          id: "image:fal-edit-2.7",
          name: "Wan 2.7 Edit (fal.ai)",
          provider: "fal.ai",
          type: "image",
          inputType: "image",
          requiresImage: true,
          safetyFilter: "disabled",
          pricing: "$0.03/image",
          parameters: {
            prompt: { type: "string", required: true, maxLength: 5000, description: "Reference images as 'image 1', 'image 2', etc. Supports Chinese and English" },
            negativePrompt: { type: "string", required: false, maxLength: 500 },
            imageSize: { type: "string", options: ["square_hd", "square", "portrait_4_3", "portrait_16_9", "landscape_4_3", "landscape_16_9"], default: "square_hd" },
            numImages: { type: "number", min: 1, max: 4, default: 1 },
            enablePromptExpansion: { type: "boolean", default: true },
            editImages: { type: "file[]", required: true, accept: "image/*", min: 1, max: 4, description: "1-4 reference images for editing" },
          },
        },
        {
          id: "image:fal-pro-edit-2.7",
          name: "Wan 2.7 Pro Edit (fal.ai)",
          provider: "fal.ai",
          type: "image",
          inputType: "image",
          requiresImage: true,
          safetyFilter: "disabled",
          pricing: "$0.075/image",
          parameters: {
            prompt: { type: "string", required: true, maxLength: 5000, description: "Reference images as 'image 1', 'image 2', etc. Supports Chinese and English" },
            negativePrompt: { type: "string", required: false, maxLength: 500 },
            imageSize: { type: "string", options: ["square_hd", "square", "portrait_4_3", "portrait_16_9", "landscape_4_3", "landscape_16_9"], default: "square_hd" },
            numImages: { type: "number", min: 1, max: 4, default: 1 },
            enablePromptExpansion: { type: "boolean", default: true },
            editImages: { type: "file[]", required: true, accept: "image/*", min: 1, max: 4, description: "1-4 reference images for editing" },
          },
        },
      ],
      supportedFileTypes: {
        image: ["image/png", "image/jpeg", "image/webp", "image/gif"],
        video: ["video/mp4", "video/webm", "video/mov"],
        "3d": [
          "model/gltf-binary",
          "model/gltf+json",
          "application/octet-stream",
          "model/obj",
          "model/stl",
          "model/fbx",
          "model/usdz",
          "model/step",
          "model/3mf",
        ],
      },
      supportedFileExtensions: {
        image: [".png", ".jpg", ".jpeg", ".webp", ".gif"],
        video: [".mp4", ".webm", ".mov", ".m4v"],
        "3d": [".glb", ".gltf", ".obj", ".stl", ".fbx", ".usdz", ".usdc", ".usd", ".step", ".stp", ".3mf", ".ply", ".abc"],
      },
    });
  } catch {
    return NextResponse.json({ success: false, message: "Unauthorized" }, { status: 401 });
  }
}
